spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myser
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.springframework: DEBUG
    com.example.Notification: INFO